name: Lint

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5"

      - name: Install Python dependencies
        run: pip install black flake8 mypy autopep8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: false
          mypy: true
          mypy_auto_fix: false
          autopep8: true
          autopep8_auto_fix: true
