name: Lint

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Install Python dependencies
        run: pip install -r requirements_dev.txt

      - name: Install types for Mypy
        run: python -m mypy --install-types

      - name: Run linters
        uses: wearerequired/lint-action@v2.0.1
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          flake8: true
          flake8_auto_fix: false
          mypy: true
          mypy_auto_fix: false
          mypy_args: "--config-file=./.mypy"
          autopep8: true
          autopep8_auto_fix: true
